# Generated by Django 2.2.1 on 2019-06-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('emailid', models.EmailField(max_length=50)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('marks', models.IntegerField(blank=True, default=0, null=True)),
                ('dat', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
